### ISSUE TITLE
Audio device WASAPI crashes due to threading issue

### ISSUE THREAD

**Issue by ashikns** [webrtc-uwp/zzz-obsolete.webrtc#1]
audio_device_wasapi_win.cc crashes on lines 377-383 and 621-627. This is due to audio buffer being accessed from the wrong thread. This can be fixed by moving the code to InitiMicrophone() and InitSpeaker() methods.

Please note that I am working with M57 of webrtc, and uses an overall different project structure. I can send in a pull request if you like, but I just wanted to make sure the issue exists in webrtc-uwp as well :)

**Comment by morosev** [comment]
@ashikns Thank you for reporting this issue. Yes, new check for the current thread has been added to AudioDeviceBuffer property setter. webrtc-uwp follows M54 on development branch and this thread check has not been included there yet. So, we are probably safe to use the current code for webrtc-uwp, but this is something that must be fixed before the next webrtc merger.
I agree that moving the problematic code to InitiMicrophone() and InitSpeaker() is a proper fix. We will apply the same approach, certainly.
@robin-raymond @SergioOpenPeer
